name: 运行资讯推送脚本

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: 安装依赖
        run: pip install feedparser  # 只需要这一个依赖
      - name: 运行脚本
        run: python news_push.py
        env:
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
      - name: 保存last_link
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add last_link.txt
          git commit -m "Update last link" || true
          git push

